name = "RandomCorrelationMatrices"
uuid = "2547b907-48b9-5396-a2af-edc57bff161c"
repo = "https://github.com/IainNZ/RandomCorrelationMatrices.jl.git"
version = "1.1.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Aqua = "0.8"
Distributions = "0.25"
LinearAlgebra = "1"
Random = "1"
Statistics = "1"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "Random", "Statistics"]
